[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

#Allow 0 to be input into the text field
[[patches]]
[patches.pattern]
target = 'engine/controller.lua'
pattern = '''
if self.text_input_hook then
'''
position = 'before'
payload = '''
if self.text_input_hook and string.sub(self.text_input_id,1,7) == "palette" then
    if string.sub(self.text_input_id,-3) == "hex" then
        G.FUNCS.palette_text_input_key_hex{
            e=self.text_input_hook,
            key = key,
            caps = true
        }
    elseif string.sub(self.text_input_id,-3) == "jid" then
        G.FUNCS.palette_text_input_key_jid{
            e=self.text_input_hook,
            key = key,
            caps = self.held_keys["lshift"] or self.held_keys["rshift"]
        }
    end
    return
end

'''
match_indent = true