[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

#Allow 0 to be input into the text field
[[patches]]
[patches.pattern]
target = 'engine/controller.lua'
pattern = '''
            G.FUNCS.text_input_key{
                e=self.text_input_hook,
                key = key,
                caps = self.held_keys["lshift"] or self.held_keys["rshift"]
            }
'''
position = 'at'
payload = '''
if string.sub(self.text_input_id,1,7) == "palette" then
    G.FUNCS.palette_text_input_key{
        e=self.text_input_hook,
        key = key,
        caps = true
    }
    sendInfoMessage("Working")
else
    G.FUNCS.text_input_key{
        e=self.text_input_hook,
        key = key,
        caps = self.held_keys["lshift"] or self.held_keys["rshift"]
    }
    sendInfoMessage("Not Working")
    sendInfoMessage(string.sub(self.text_input_id,1,7))
end
'''
match_indent = true